

export const FIND_PROVINCE_REQUEST = "FIND_PROVINCE_REQUEST";
export const FIND_PROVINCE_SUCCESS = "FIND_PROVINCE_SUCCESS";
export const FIND_PROVINCE_FAILURE = "FIND_PROVINCE_FAILURE";

export const FIND_PROVINCES_REQUEST = "FIND_PROVINCES_REQUEST";
export const FIND_PROVINCES_SUCCESS = "FIND_PROVINCES_SUCCESS";
export const FIND_PROVINCES_FAILURE = "FIND_PROVINCES_FAILURE";

export const SAVE_PROVINCE_REQUEST = "SAVE_PROVINCE_REQUEST";
export const SAVE_PROVINCE_SUCCESS = "SAVE_PROVINCE_SUCCESS";
export const SAVE_PROVINCE_FAILURE = "SAVE_PROVINCE_FAILURE";

export const DELETE_PROVINCE_REQUEST = "DELETE_PROVINCE_REQUEST";
export const DELETE_PROVINCE_SUCCESS = "DELETE_PROVINCE_SUCCESS";
export const DELETE_PROVINCE_FAILURE = "DELETE_PROVINCE_FAILURE";

export const DELETE_PROVINCES_REQUEST = "DELETE_PROVINCES_REQUEST";
export const DELETE_PROVINCES_SUCCESS = "DELETE_PROVINCES_SUCCESS";
export const DELETE_PROVINCES_FAILURE = "DELETE_PROVINCES_FAILURE";

export const FIND_CONTRACEPTION_REQUEST = "FIND_CONTRACEPTION_REQUEST";
export const FIND_CONTRACEPTION_SUCCESS = "FIND_CONTRACEPTION_SUCCESS";
export const FIND_CONTRACEPTION_FAILURE = "FIND_CONTRACEPTION_FAILURE";

export const FIND_CONTRACEPTIONS_REQUEST = "FIND_CONTRACEPTIONS_REQUEST";
export const FIND_CONTRACEPTIONS_SUCCESS = "FIND_CONTRACEPTIONS_SUCCESS";
export const FIND_CONTRACEPTIONS_FAILURE = "FIND_CONTRACEPTIONS_FAILURE";

export const SAVE_CONTRACEPTION_REQUEST = "SAVE_CONTRACEPTION_REQUEST";
export const SAVE_CONTRACEPTION_SUCCESS = "SAVE_CONTRACEPTION_SUCCESS";
export const SAVE_CONTRACEPTION_FAILURE = "SAVE_CONTRACEPTION_FAILURE";

export const DELETE_CONTRACEPTION_REQUEST = "DELETE_CONTRACEPTION_REQUEST";
export const DELETE_CONTRACEPTION_SUCCESS = "DELETE_CONTRACEPTION_SUCCESS";
export const DELETE_CONTRACEPTION_FAILURE = "DELETE_CONTRACEPTION_FAILURE";

export const DELETE_CONTRACEPTIONS_REQUEST = "DELETE_CONTRACEPTIONS_REQUEST";
export const DELETE_CONTRACEPTIONS_SUCCESS = "DELETE_CONTRACEPTIONS_SUCCESS";
export const DELETE_CONTRACEPTIONS_FAILURE = "DELETE_CONTRACEPTIONS_FAILURE";

export const FIND_CONTRACEPTION_USER_REQUEST = "FIND_CONTRACEPTION_USER_REQUEST";
export const FIND_CONTRACEPTION_USER_SUCCESS = "FIND_CONTRACEPTION_USER_SUCCESS";
export const FIND_CONTRACEPTION_USER_FAILURE = "FIND_CONTRACEPTION_USER_FAILURE";

export const FIND_CONTRACEPTION_USERS_REQUEST = "FIND_CONTRACEPTION_USERS_REQUEST";
export const FIND_CONTRACEPTION_USERS_SUCCESS = "FIND_CONTRACEPTION_USERS_SUCCESS";
export const FIND_CONTRACEPTION_USERS_FAILURE = "FIND_CONTRACEPTION_USERS_FAILURE";

export const SAVE_CONTRACEPTION_USER_REQUEST = "SAVE_CONTRACEPTION_USER_REQUEST";
export const SAVE_CONTRACEPTION_USER_SUCCESS = "SAVE_CONTRACEPTION_USER_SUCCESS";
export const SAVE_CONTRACEPTION_USER_FAILURE = "SAVE_CONTRACEPTION_USER_FAILURE";

export const DELETE_CONTRACEPTION_USER_REQUEST = "DELETE_CONTRACEPTION_USER_REQUEST";
export const DELETE_CONTRACEPTION_USER_SUCCESS = "DELETE_CONTRACEPTION_USER_SUCCESS";
export const DELETE_CONTRACEPTION_USER_FAILURE = "DELETE_CONTRACEPTION_USER_FAILURE";

export const DELETE_CONTRACEPTION_USERS_REQUEST = "DELETE_CONTRACEPTION_USERS_REQUEST";
export const DELETE_CONTRACEPTION_USERS_SUCCESS = "DELETE_CONTRACEPTION_USERS_SUCCESS";
export const DELETE_CONTRACEPTION_USERS_FAILURE = "DELETE_CONTRACEPTION_USERS_FAILURE";

export const FIND_TRANSACTION_REQUEST = "FIND_TRANSACTION_REQUEST";
export const FIND_TRANSACTION_SUCCESS = "FIND_TRANSACTION_SUCCESS";
export const FIND_TRANSACTION_FAILURE = "FIND_TRANSACTION_FAILURE";

export const FIND_TRANSACTIONS_REQUEST = "FIND_TRANSACTIONS_REQUEST";
export const FIND_TRANSACTIONS_SUCCESS = "FIND_TRANSACTIONS_SUCCESS";
export const FIND_TRANSACTIONS_FAILURE = "FIND_TRANSACTIONS_FAILURE";

export const SAVE_TRANSACTION_REQUEST = "SAVE_TRANSACTION_REQUEST";
export const SAVE_TRANSACTION_SUCCESS = "SAVE_TRANSACTION_SUCCESS";
export const SAVE_TRANSACTION_FAILURE = "SAVE_TRANSACTION_FAILURE";

export const DELETE_TRANSACTION_REQUEST = "DELETE_TRANSACTION_REQUEST";
export const DELETE_TRANSACTION_SUCCESS = "DELETE_TRANSACTION_SUCCESS";
export const DELETE_TRANSACTION_FAILURE = "DELETE_TRANSACTION_FAILURE";

export const DELETE_TRANSACTIONS_REQUEST = "DELETE_TRANSACTIONS_REQUEST";
export const DELETE_TRANSACTIONS_SUCCESS = "DELETE_TRANSACTIONS_SUCCESS";
export const DELETE_TRANSACTIONS_FAILURE = "DELETE_TRANSACTIONS_FAILURE";
