application.data-dir: ./assets
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/DB_Keluarga_Berencana
        username: root
        password: 
        initialization-mode: always
        platform: mysql
    jpa:
        hibernate:
            ddl-auto: none
        generate-ddl: true
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    messages:
        basename: i18n/messages
    servlet:
        multipart:
            enabled: true
            max-file-size: 2MB
            max-request-size: 2MB
server:
    port: 3010